"""
Script to generate benchmarks/generator_internals.md from the current code definitions.
Run this whenever you modify generator descriptions or configurations.
"""

import sys
import os
from pathlib import Path

# Add project root to sys.path
project_root = Path(__file__).resolve().parent.parent
sys.path.append(str(project_root))

from benchmarks.benchmark_candidates import CANDIDATE_GENERATORS

def generate_docs():
    output_path = project_root / "benchmarks" / "generator_internals.md"
    
    content = ["# Generator Internals\n"]
    content.append("> This file is auto-generated by `tools/update_generator_docs.py`. Do not edit manually.\n")
    
    for g in CANDIDATE_GENERATORS:
        model_name = getattr(g, "model_name", "Unknown")
        desc = getattr(g, "description", "No description provided.")
        image_name = getattr(g, "image_name", None)
        
        content.append(f"### {g.name}")
        content.append(f"- **Model:** `{model_name}`")
        if image_name:
            content.append(f"- **Docker Image:** `{image_name}`")
        
        # Clean up description indentation if needed
        desc_clean = desc.strip()
        content.append(f"\n{desc_clean}\n")
        content.append("---\n")
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(content))
    
    print(f"Successfully generated {output_path}")
    print(f"Contains {len(CANDIDATE_GENERATORS)} generators.")

if __name__ == "__main__":
    generate_docs()
